// Automatically generated by astro-icon
// d197332a9796b72990e5117bcef3bccdddf84b826a85d5a9619214c192c91d5c

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "menu/about"
		| "menu/blog"
		| "menu/categories"
		| "menu/contact"
		| "menu/cube"
		| "menu/friend"
		| "menu/heart"
		| "menu/home"
		| "menu/post"
		| "menu/project"
		| "social/bilibili"
		| "social/github"
		| "social/rss"
		| "social/support"
		| "social/zhihu";
}